# Generated by Django 2.0.6 on 2018-11-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Description',
        ),
        migrations.AddField(
            model_name='article',
            name='desc',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
