# Generated by Django 2.0.6 on 2018-11-21 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_paragraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='article',
        ),
        migrations.DeleteModel(
            name='Paragraph',
        ),
    ]
